import Link from "next/link";
import JsonLd from "@/components/seo/JsonLd";
import { Cta, Faq, PageHeader, Section } from "@/components/ui";
import { catalogProducts, productRequestHref } from "@/content/data/catalog";
import { buildPageMetadata, buildWebPageSchema } from "@/lib/seo";

const path = "/sourcing/china";
const description = "Source architectural panels from China with Cladvera. Plan RFQs, origin records, technical evidence and import scope for US and Canadian projects.";
export const metadata = buildPageMetadata({ title: "China-Sourced Architectural Panels | Cladvera", description, path });
const textLink = "text-accent underline underline-offset-4 hover:text-accent-hover";

const ranges = [
  { name: "Metal composite panels", manufacturer: "ALMINE", href: "/materials/acm-panels", ids: ["almine-a2", "almine-tunnel", "almine-medical"], inputs: "Face metal and gauge; core and total thickness; flat sheet or fabricated cassette; coating, dimensions, joint layout and quantity.", evidence: "Identify the exact construction in fire and assembly evidence. Add transit-authority requirements or healthcare cleaning and surface-report needs where relevant." },
  { name: "Exterior HPL facade panels", manufacturer: "Compactwood", href: "/materials/exterior-hpl-panels", ids: ["compactwood-exterior"], inputs: "Exterior grade, board thickness and format; finish and grain direction; exposed edges, fixing method, cut list and quantity.", evidence: "Request the offered grade's weathering, fire and installation documents, plus samples and attachment details for the project." },
  { name: "Interior decorative boards", manufacturer: "Compactwood", href: "/materials/interior-hpl-panels", ids: ["compactwood-interior"], inputs: "Interior use and offered core; thickness, decorative face, substrate, adhesive or mechanical fixing, cleaning regime and quantity.", evidence: "Confirm the board construction and interior-finish evidence. The interior family is not confirmed as HPL and should not inherit exterior HPL specifications." },
  { name: "Custom GFRP architectural elements", manufacturer: "Shandong Jinguang Group / Kinflare", href: "/materials/gfrp-custom-elements", ids: ["gfrp-custom"], inputs: "3D model and drawing revision; module sizes, tolerances, resin and laminate proposal, finish, fixing zones, repeated quantities and mold ownership.", evidence: "Define prototype acceptance, support loads, connection design and required fire evidence. Assign responsibility for engineering and interface review." },
];

const quoteScope = [
  { item: "Product and preparation", check: "Named manufacturer, construction, finish, dimensions, unit basis, net quantity, cutting or fabrication, accessories and agreed spare parts." },
  { item: "Development and approval", check: "Samples, drawings, testing or engineering scope, tooling, mock-ups and any agreed inspection. Show separate charges and approval conditions." },
  { item: "Export packing and shipment", check: "Crate construction, handling orientation, packing quantities, weights, shipment dimensions, freight and insurance inclusions, and split-delivery assumptions." },
  { item: "Delivery and import allocation", check: "Agreed Incoterm, version and named place; exporter and importer identities; clearance, brokerage, duties, taxes, unloading and site access responsibilities." },
  { item: "Commercial and schedule basis", check: "Currency, payment, quote validity, change process and milestones from sample/drawing approval through release, shipment and receipt." },
];

const questions = [
  { q: "Is Cladvera the manufacturer of the panels?", a: "Cladvera is a supplier coordinating material selection and project supply. ALMINE, Compactwood and the named GFRP supplier provide the product references for these China-sourcing ranges. The quotation should identify the offered manufacturer, product construction and supply scope." },
  { q: "Are TAKTL UHPC products part of the China-sourcing range?", a: "No. TAKTL is a separate US manufacturer reference in the Cladvera catalogue. Its products, documentation and project supply must be reviewed separately; the presence of TAKTL in the catalogue does not make it a China-origin product." },
  { q: "What is needed to request a China-sourced panel quotation?", a: "Provide the project location and use, named product or material direction, quantities and units, dimensions or drawing revision, finish references, required technical evidence and target schedule. Add the delivery destination and the import or logistics responsibilities you want clarified. Use the material-specific checklist on this page for construction details." },
  { q: "Does shipping from China establish the country of origin?", a: "Country of manufacture and ship-from location are separate records. Ask for the manufacturer, production location, exporter, dispatch point and supporting origin information for the offered goods. The importer and its adviser should confirm the origin and customs treatment for the specific shipment." },
  { q: "Can a tariff rate, delivered price or lead time be confirmed from a material name?", a: "A generic label such as HPL, ACM or GFRP is not enough. Product composition, construction, origin, quantity, delivery destination and the agreed scope must first be defined. Classification and current import charges require shipment-specific review; pricing and timing are confirmed in the project quotation." },
  { q: "Does import clearance mean the panel is approved for the building?", a: "Import planning and building approval are separate reviews. The design team must match the exact product and proposed assembly to the project's jurisdiction, use and evidence requirements. A manufacturer brochure, product designation or reference project is not a project approval." },
];

export default function Page() {
  return <>
    <JsonLd data={buildWebPageSchema({ name: "China-sourced architectural panels and export procurement", description, path })} />
    <PageHeader eyebrow="China sourcing / Project supply" title="Source architectural panels from China." lede="Cladvera coordinates China-sourced metal composite panels, exterior HPL, interior decorative boards and custom GFRP for project teams in the United States and Canada. Define the product, evidence and export scope before order release." crumbs={[{ name: "China sourcing", path }]} actions={<><Cta href="/request-quote">Prepare a sourcing brief <span aria-hidden="true">↗</span></Cta><Cta href="#product-scope" variant="secondary">Review material requirements</Cta></>}>
      <p className="mt-[24px] max-w-[740px] border-l-2 border-accent pl-[20px] text-f14 leading-[1.8] text-ink-2">Cladvera is a supplier. Manufacturing, product documentation and origin belong to the named offered product; sample availability, order scope and commercial terms are confirmed for each project.</p>
    </PageHeader>

    <nav aria-label="China sourcing page sections" className="border-b border-line">
      <div className="site-container grid grid-cols-2 gap-x-[24px] md:grid-cols-4">
        {[{ href: "#product-scope", label: "Materials & RFQ inputs" }, { href: "#quote-scope", label: "Quote scope" }, { href: "#import-planning", label: "Import planning" }, { href: "#questions", label: "Buyer questions" }].map((item, index) => <Link key={item.href} href={item.href} className="flex min-h-[72px] items-center gap-[12px] py-[18px] text-f12 text-ink-2 hover:text-accent"><span className="font-mono text-[10px] text-accent">0{index + 1}</span>{item.label}</Link>)}
      </div>
    </nav>

    <Section id="product-scope" title="A material name is the starting point." lede="Use these construction-specific inputs to turn a product reference into an RFQ. Name the exact manufacturer and family; leave unresolved items visibly marked for confirmation.">
      <div role="region" aria-label="Material-specific sourcing checklist" tabIndex={0} className="overflow-x-auto border-y border-line-strong">
        <table className="w-full min-w-[780px] border-collapse text-left text-f14">
          <caption className="sr-only">China-associated material ranges, RFQ inputs and evidence to review</caption>
          <thead><tr className="border-b border-line-strong"><th scope="col" className="w-[25%] py-[18px] pr-[24px] font-mono text-[10px] font-normal uppercase tracking-[0.08em] text-ink-3">Material / source</th><th scope="col" className="w-[37%] px-[24px] py-[18px] font-mono text-[10px] font-normal uppercase tracking-[0.08em] text-ink-3">Include in the RFQ</th><th scope="col" className="pl-[24px] py-[18px] font-mono text-[10px] font-normal uppercase tracking-[0.08em] text-ink-3">Evidence &amp; decisions</th></tr></thead>
          <tbody>{ranges.map(range => <tr key={range.href} className="border-b border-line last:border-b-0"><th scope="row" className="py-[24px] pr-[24px] align-top font-normal"><Link href={range.href} className={`${textLink} font-medium`}>{range.name}</Link><span className="mt-[10px] block text-f12 text-ink-3">{range.manufacturer}</span></th><td className="px-[24px] py-[24px] align-top leading-[1.8] text-ink-2">{range.inputs}</td><td className="py-[24px] pl-[24px] align-top leading-[1.8] text-ink-2">{range.evidence}</td></tr>)}</tbody>
        </table>
      </div>
      <p className="mt-[12px] text-f12 text-ink-3 md:hidden">Scroll the checklist horizontally to read all columns.</p>
      <div className="mt-[32px] grid gap-x-[32px] gap-y-[24px] md:grid-cols-2">
        {ranges.map(range => <div key={range.href} className="border-t border-line pt-[18px]"><h3 className="text-f14 font-medium">Start with a named candidate</h3><ul className="mt-[12px] grid gap-[10px]">{range.ids.map(id => { const product = catalogProducts.find(item => item.id === id)!; return <li key={id} className="flex flex-wrap items-baseline justify-between gap-x-[16px] gap-y-[4px]"><Link href={product.path} className="inline-flex min-h-[44px] items-center text-f14 text-ink-2 hover:text-accent">{product.name}</Link><Link href={productRequestHref(id)} aria-label={`Prepare an RFQ for ${product.name}`} className="inline-flex min-h-[44px] items-center gap-[12px] text-f12 text-accent underline underline-offset-4">Prepare RFQ <span aria-hidden="true">↗</span></Link></li>; })}</ul></div>)}
      </div>
      <aside className="mt-[36px] grid gap-[14px] border-t border-line-strong pt-[24px] md:grid-cols-[220px_1fr] md:gap-[40px]"><h3 className="font-mono text-[11px] uppercase tracking-[0.08em]">TAKTL: a separate source</h3><p className="max-w-[800px] text-f14 leading-[1.8] text-ink-2"><Link href="/suppliers/taktl" className={textLink}>TAKTL architectural UHPC</Link> is a US manufacturer range, separate from the China-sourcing materials above. TAKTL identifies its manufacturing in Pittsburgh, Pennsylvania in its <a href="https://www.taktl-llc.com/taktl-news/" target="_blank" rel="noopener noreferrer" className={textLink}>manufacturer publications<span className="sr-only"> (opens in a new tab)</span></a>. Review its product and project supply independently.</p></aside>
      <div className="mt-[28px] flex flex-wrap gap-x-[28px] gap-y-[12px]"><Cta href="/guides/facade-materials" variant="ghost">Compare facade material routes <span aria-hidden="true">↗</span></Cta><Cta href="/technical-resources" variant="ghost">Review product documents <span aria-hidden="true">↗</span></Cta></div>
    </Section>

    <Section id="quote-scope" tone="muted" title="Compare the offer, line by line." lede="A comparable quotation makes inclusions, exclusions and unconfirmed items visible. Request the scope below before comparing unit prices.">
      <dl className="border-t border-line-strong">{quoteScope.map((row, index) => <div key={row.item} className="grid gap-[16px] border-b border-line py-[24px] md:grid-cols-[280px_1fr] md:gap-[40px]"><dt className="flex gap-[18px] text-f16 font-medium"><span aria-hidden="true" className="pt-[4px] font-mono text-[10px] text-accent">0{index + 1}</span>{row.item}</dt><dd className="max-w-[780px] text-f14 leading-[1.8] text-ink-2">{row.check}</dd></div>)}</dl>
      <p className="mt-[24px] max-w-[900px] text-f14 leading-[1.8] text-ink-2">Trade terms allocate tasks, costs and risk; they do not replace the product description, payment agreement or acceptance criteria. Record the term, named place and version in the offer. See the <a href="https://www.trade.gov/know-your-incoterms" target="_blank" rel="noopener noreferrer" className={textLink}>International Trade Administration&apos;s Incoterms overview<span className="sr-only"> (opens in a new tab)</span></a>. The available delivery basis is confirmed for the project.</p>
      <div className="mt-[20px]"><Cta href="/procurement" variant="ghost">Follow the RFQ-to-delivery workflow <span aria-hidden="true">↗</span></Cta></div>
    </Section>

    <Section id="import-planning" title="Plan the shipment and the project review." lede="Confirm the origin, shipment route and responsible parties against the actual offered goods. Customs entry and approval for use in a building require different information.">
      <div className="grid gap-[40px] lg:grid-cols-2 lg:gap-[64px]">
        <div><h3 className="border-b border-line-strong pb-[16px] text-f20 font-medium">Origin &amp; shipment record</h3><ul className="mt-[18px] grid gap-[14px] text-f14 leading-[1.8] text-ink-2">{["Record the manufacturer and production location separately from the seller, exporter and ship-from address.", "Provide the product composition, intended use, dimensions and technical description to the importer and customs adviser; do not assign customs treatment from a catalogue label alone.", "Agree the invoice, packing list, transport record and supporting origin or composition information needed for the shipment.", "Confirm packing material, crate weights and dimensions, lifting/unloading access and any phased or split deliveries."].map(item => <li key={item} className="border-b border-line pb-[14px]">{item}</li>)}</ul></div>
        <div><h3 className="border-b border-line-strong pb-[16px] text-f20 font-medium">Two destination checks</h3><div className="mt-[18px] grid gap-[24px]"><div><h4 className="mb-[8px] text-f14 font-medium">United States</h4><p className="text-f14 leading-[1.8] text-ink-2">Identify the importer of record and any customs broker before shipment. CBP explains that engaging a broker does not remove the importer&apos;s responsibility to understand import requirements. Ask the importer&apos;s adviser to review classification, origin, entry data and applicable charges for the offered goods.</p><a href="https://www.help.cbp.gov/s/article/Article-1169?language=en_US" target="_blank" rel="noopener noreferrer" className={`${textLink} mt-[10px] inline-flex min-h-[44px] items-center text-f12`}>CBP: importers and customs brokers<span className="sr-only"> (opens in a new tab)</span></a></div><div><h4 className="mb-[8px] text-f14 font-medium">Canada</h4><p className="text-f14 leading-[1.8] text-ink-2">CBSA asks importers to gather descriptions, composition and origin information; country of origin may differ from the dispatch country. Classification, origin and value inform import treatment. For building use, NRC explains that approval is assessed under the applicable local jurisdiction and proposed use.</p><div className="mt-[10px] flex flex-wrap gap-x-[20px] gap-y-[8px] text-f12"><a href="https://www.cbsa-asfc.gc.ca/import/guide-2-eng.html" target="_blank" rel="noopener noreferrer" className={`${textLink} inline-flex min-h-[44px] items-center`}>CBSA: product and origin information<span className="sr-only"> (opens in a new tab)</span></a><a href="https://www.cbsa-asfc.gc.ca/import/guide-3-eng.html" target="_blank" rel="noopener noreferrer" className={`${textLink} inline-flex min-h-[44px] items-center`}>CBSA: classification and import charges<span className="sr-only"> (opens in a new tab)</span></a><a href="https://nrc.canada.ca/en/certifications-evaluations-standards/canadian-construction-materials-centre/construction-product-approvals-canada" target="_blank" rel="noopener noreferrer" className={`${textLink} inline-flex min-h-[44px] items-center`}>NRC: construction product approvals<span className="sr-only"> (opens in a new tab)</span></a></div></div></div></div>
      </div>
      <div className="mt-[36px] grid gap-[16px] border-t border-line-strong pt-[24px] md:grid-cols-[220px_1fr] md:gap-[40px]"><h3 className="font-mono text-[11px] uppercase tracking-[0.08em]">Confirm the packaging</h3><p className="max-w-[880px] text-f14 leading-[1.8] text-ink-2">For regulated wood crates, pallets or dunnage, confirm the destination&apos;s treatment and marking requirements. Packaging construction matters; requirements are not identical for every wood-based material. Consult <a href="https://www.aphis.usda.gov/plant-imports/wood-packaging-material" target="_blank" rel="noopener noreferrer" className={textLink}>USDA APHIS wood-packaging guidance<span className="sr-only"> (opens in a new tab)</span></a> and <a href="https://inspection.canada.ca/en/plant-health/forestry/imports/wood-packaging" target="_blank" rel="noopener noreferrer" className={textLink}>CFIA wood-packaging guidance<span className="sr-only"> (opens in a new tab)</span></a>.</p></div>
    </Section>

    <Section id="questions" tone="muted"><Faq items={questions} title="Questions before sourcing panels from China" /></Section>
    <Section><div className="grid gap-[28px] border-t border-ink pt-[28px] lg:grid-cols-2 lg:gap-[64px]"><h2 className="editorial-title max-w-[560px]">Make the next<br /><span className="editorial-serif">decision specific.</span></h2><div><p className="max-w-[560px] text-f16 leading-[1.8] text-ink-2">Bring the material shortlist, drawing revision, destination and required evidence. Use the project brief to identify what is known and what needs confirmation.</p><div className="mt-[24px] flex flex-wrap gap-[12px]"><Cta href="/request-quote">Prepare a project request</Cta><Cta href="/technical-resources" variant="secondary">Find technical documents</Cta></div></div></div></Section>
  </>;
}
