import Image from "next/image";
import Link from "next/link";
import { Section, Cta, LinkCard } from "@/components/ui";
import { catalogCategories, catalogApplications } from "@/content/data/catalog";
import { buildPageMetadata } from "@/lib/seo";
export const metadata = buildPageMetadata({ title: "Architectural Materials & Custom Elements | Cladvera", description: "Explore architectural UHPC, metal composite, HPL and custom GFRP. Compare product families and coordinate samples, technical documents and project procurement.", path: "/" });
export default function Page() {
  return <>
    <section className="border-b border-line bg-paper-2"><div className="site-container grid items-center gap-[36px] py-[48px] md:py-[64px] lg:grid-cols-[1.1fr_0.9fr]">
      <div><p className="font-mono text-f12 uppercase tracking-[0.1em] text-accent">Architectural materials · project supply</p><h1 className="mt-[16px] max-w-[700px] text-f44 font-semibold">From material intent<br />to a defined supply brief.</h1><p className="mt-[20px] max-w-[640px] text-f18 text-ink-2">Explore facade panels, interior surfaces and custom architectural forms. Cladvera connects product selection with the samples, documents and commercial scope your project needs.</p><div className="mt-[28px] flex flex-wrap gap-[12px]"><Cta href="/products">Explore products</Cta><Cta href="/applications" variant="secondary">Browse by application</Cta></div></div>
      <figure className="overflow-hidden rounded-card border border-line bg-paper"><div className="relative h-[300px] md:h-[380px]"><Image src="/images/compactwood/supplier-project.jpg" alt="Facade project shown by Compactwood in its manufacturer reference gallery" fill sizes="(min-width: 1024px) 45vw, 100vw" className="object-cover" priority /></div><figcaption className="px-[16px] py-[12px] text-f12 text-ink-3">Compactwood manufacturer project reference. Product and assembly selection are confirmed separately.</figcaption></figure>
    </div></section>
    <Section title="Start with a material" lede="Distinct families, clear product roles and named manufacturer sources."><div className="grid gap-[16px] md:grid-cols-2 lg:grid-cols-3">{catalogCategories.map((c, i) => <LinkCard key={c.id} href={`/products?category=${c.id}`} title={c.label} description={c.description} meta={<span className="font-mono text-f12 text-accent">0{i + 1}</span>} />)}</div></Section>
    <Section title="Two routes. One coordinated selection." tone="muted"><div className="grid gap-[20px] md:grid-cols-2"><LinkCard href="/architects" title="For architects & designers" description="Compare materials, establish finish intent, plan samples and identify the evidence needed for a project specification." meta="DESIGN → SPECIFICATION" /><LinkCard href="/procurement" title="For buyers & project teams" description="Turn approved intent into quantities, document requirements, scope boundaries and a request for commercial terms." meta="SCOPE → ORDER → DELIVERY" /></div></Section>
    <Section title="Select for the application"><div className="grid gap-[12px] md:grid-cols-2 lg:grid-cols-3">{catalogApplications.map(a => <LinkCard key={a.id} href={`/products?application=${a.id}`} title={a.label} description={a.description} />)}</div></Section>
    <Section title="Keep the decision connected" tone="muted"><ol className="grid gap-[16px] md:grid-cols-4">{[["01", "Find candidates", "Filter materials and applications.", "/products"], ["02", "Build a shortlist", "Compare the construction and document needs.", "/compare"], ["03", "Review the evidence", "Request samples and project-specific documents.", "/technical-resources"], ["04", "Define the request", "Share drawings, quantities, finish and timing.", "/request-quote"]].map(([n,title,body,href]) => <li key={n} className="rounded-card border border-line bg-paper p-[20px]"><p className="font-mono text-f12 text-accent">{n}</p><Link href={href} className="mt-[8px] block text-f18 font-semibold hover:text-accent">{title} →</Link><p className="mt-[8px] text-f14 text-ink-2">{body}</p></li>)}</ol></Section>
  </>;
}
